//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Spiridonov Maxim @taijased
//

import UIKit

class ___VARIABLE_productName:identifier___Presenter: ___VARIABLE_productName:identifier___PresenterProtocol {
    weak var view: ___VARIABLE_productName:identifier___ViewProtocol!
    var interactor: ___VARIABLE_productName:identifier___InteractorProtocol!
    var router: ___VARIABLE_productName:identifier___RouterProtocol!
    
    required init(view: ___VARIABLE_productName:identifier___ViewProtocol) {
        self.view = view
    }

}
