//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Spiridonov Maxim @taijased
//

import Foundation
import UIKit
//MARK: Router -
protocol ___VARIABLE_productName:identifier___RouterProtocol: class {
    func prepare(for segue: UIStoryboardSegue, sender: Any?)

}
//MARK: Presenter -
protocol ___VARIABLE_productName:identifier___PresenterProtocol: class {
    var router:  ___VARIABLE_productName:identifier___RouterProtocol! { set get }
    func configureView()
}

//MARK: Interactor -
protocol ___VARIABLE_productName:identifier___InteractorProtocol: class {

}

//MARK: View -
protocol ___VARIABLE_productName:identifier___ViewProtocol: class {

}

//MARK: Configurator -
protocol ___VARIABLE_productName:identifier___ConfiguratorProtocol: class {
    func configure(with viewController: ___VARIABLE_productName:identifier___ViewController)
}

